global:
  scrape_interval: 10s
scrape_configs:
  - job_name: 'application'
    #metrics_path: '/actuator/prometheus'
    static_configs:
      - targets:
          - 'host.docker.internal:9000' #client
          - 'host.docker.internal:9001' #worker 1
          - 'host.docker.internal:9002' #worker 2
          - 'host.docker.internal:9003' #worker 3


