global:
  scrape_interval: 10s
scrape_configs:
  - job_name: 'python_core_metrics'
    static_configs:
      - targets:
          - 'host.docker.internal:8085'
          - 'host.docker.internal:8086'
        labels:
          source: 'python_metric'