version: "3.5"
services:
#  jaeger-all-in-one:
#    image: jaegertracing/all-in-one:latest
#    ports:
#      - "16686:16686"
#      - "14268"
#      - "14250"
    # Collector

#  prometheus:
#    container_name: prometheus
#    image: prom/prometheus:v2.37.0
#    ports:
#      - 9090:9090
#    volumes:
#      - type: bind
#        source: ./prometheus/config.yml
#        target: /etc/prometheus/prometheus.yml


  otel-collector:
    image: otel/opentelemetry-collector-contrib
    volumes:
      - ./otel-collector-config.yaml:/etc/otelcol-contrib/config.yaml
    ports:
      - 1888:1888 # pprof extension
      - 8890:8890 # Prometheus metrics exposed by the Collector
      - 8889:8889 # Prometheus exporter metrics
      - 13133:13133 # health_check extension
      - 4317:4317 # OTLP gRPC receiver
      - 4318:4318 # OTLP http receiver
      - 55679:55679 # zpages extension
    networks:
      - temporal_network

networks:
  temporal_network:
    external: true