global:
  scrape_interval: 10s
scrape_configs:
  - job_name: 'ts-sdk'
    static_configs:
      - targets:
          - '127.0.0.1:9092'
          - '127.0.0.1:9091'
          - 'host.docker.internal:9091'
          - 'host.docker.internal:9092'

