global:
  scrape_interval: 10s
scrape_configs:
  - job_name: 'application'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets:
          - 'host.docker.internal:8080'
          - 'host.docker.internal:8081'
  - job_name: 'ts-sdk'
    static_configs:
      - targets:
          - 'host.docker.internal:9464'
  - job_name: 'client-java'
    static_configs:
      - targets:
          - 'host.docker.internal:8079'
          - 'host.docker.internal:8071'
  - job_name: 'client-java_test_worker'
    static_configs:
      - targets:
          - 'host.docker.internal:8073'
          - 'host.docker.internal:8072'
  - job_name: 'python_core_metrics'
    static_configs:
      - targets:
          - 'host.docker.internal:8085'
          - 'host.docker.internal:8086'
        labels:
          source: 'python_metric'
  - job_name: 'go_metrics'
    static_configs:
      - targets:
          - 'host.docker.internal:9095'
          - 'host.docker.internal:9096'
        labels:
          source: 'python_metric'

  - job_name: 'collector'
    static_configs:
      - targets:
          - 'host.docker.internal:8889'
        labels:
          source: 'collector_8889'
