

# switch to true to connect with localhost, if == true other properties will be ignored
temporal_local_server = false

temporal_namespace=antonio.a2dd6

# temporal_namespace=default

temporal_worker_target_endpoint=antonio.a2dd6.tmprl.cloud:7233


# Location of your key certificate, which should look like:
# -----BEGIN PRIVATE KEY-----
# ...
# -----END PRIVATE KEY-----
# full path to the certificate
temporal_key_location=/Users/temporalio/dev/temporal/my-temporal-pocs/java/_ZD/_14791/src/main/resources/certs/client.key
# Location of your client certificate, which should look like:
# -----BEGIN CERTIFICATE-----
# ...
# -----END CERTIFICATE-----
# full path to the certificate
temporal_cert_location=/Users/temporalio/dev/temporal/my-temporal-pocs/java/_ZD/_14791/src/main/resources/certs/client.pem
